# -*- coding: utf-8 -*-
"""DE_TASK_3_ETL.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b8peogFpFWEtfkn1eISwFgWqQC6mM8M8
"""

import pandas as pd
from sqlalchemy import create_engine
import pymysql
pymysql.install_as_MySQLdb()
import MySQLdb

ca = pd.read_csv("/content/drive/MyDrive/Datas/battles.csv")
us = pd.read_csv("/content/drive/MyDrive/Datas/character-deaths.csv")
tx = pd.read_csv("/content/drive/MyDrive/Datas/character-predictions.csv")

ca.head()

us.head()

print(ca.columns)

ca = ca[['name', 'year', 'battle_number', 'attacker_king', 'defender_king',
       'attacker_1', 'attacker_2', 'attacker_3', 'attacker_4', 'defender_1',
       'defender_2', 'defender_3', 'defender_4', 'attacker_outcome',
       'battle_type', 'major_death', 'major_capture', 'attacker_size',
       'defender_size', 'attacker_commander', 'defender_commander', 'summer',
       'location', 'region', 'note']].copy()
ca.insert(1,'country','CA')
ca

print(us.columns)

us = us[['Name', 'Allegiances', 'Death Year', 'Book of Death', 'Death Chapter',
       'Book Intro Chapter', 'Gender', 'Nobility', 'GoT', 'CoK', 'SoS', 'FfC',
       'DwD'  ]].copy()
us.insert(1,'country','US')
us

print(tx.columns)

tx = tx[['S.No', 'actual', 'pred', 'alive', 'plod', 'name', 'title', 'male',
       'culture', 'dateOfBirth', 'DateoFdeath', 'mother', 'father', 'heir',
       'house', 'spouse', 'book1', 'book2', 'book3', 'book4', 'book5',
       'isAliveMother', 'isAliveFather', 'isAliveHeir', 'isAliveSpouse',
       'isMarried', 'isNoble', 'age', 'numDeadRelations', 'boolDeadRelations',
       'isPopular', 'popularity', 'isAlive']].copy()
tx.insert(1,'country','TX')
tx

import json
from pandas.io.json import json_normalize
cat=[]

df=pd.concat([ca,us])
df = df.reset_index(drop=True)
df.insert(0,'ID',range(1,1+len(df)))
df=df.set_index('ID')
df

df.count()

pip install mysql-connector

import os
import mysql.connector
from pymysql  import connect

pip install SQLAlchemy

pip install mysql-connector-python

pip install ipython-sql

finalresult = pd.DataFrame(data = df)
print(df)
finalresult.to_sql(con=my_conn, name= 'etl', if_exists = 'append', index = False)